# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023-2025 Univention GmbH

---

include:
  - project: "univention/dev/nubus-for-k8s/common-ci"
    ref: "v1.44.4"
    file:
      - "defaults/stages.yaml"
      - "defaults/nubus-workflow.yaml"
      - "jobs/lint-pre-commit.yaml"
      - "jobs/lint-commit-messages.yaml"
      - "jobs/semantic-release-env.yaml"
      - "jobs/container-build-external.yaml"
      - "jobs/package-and-publish-helm-charts-external.yaml"
      - "jobs/check-debian-updates.yaml"
      - "templates/sonarqube.yaml"
  - project: "univention/infrastructure/docker-services"
    ref: "master"
    file:
      - "dind.yml"

.build-matrix: &build-matrix
  - IMAGE_NAME:
      - "udm-rest-api"
      - "testrunner"
  - IMAGE_NAME: "udm-rest-api-python-client"
    KANIKO_ARGS: "--target final"
    DOCKERFILE_PATH: "docker/udm-rest-api-python-client/Dockerfile"
  - IMAGE_NAME: "udm-cli"
    KANIKO_ARGS: "--target cli"
    DOCKERFILE_PATH: "docker/udm-rest-api-python-client/Dockerfile"
  - IMAGE_NAME: "ldap-update-univention-object-identifier"
    KANIKO_BUILD_CONTEXT: "$CI_PROJECT_DIR/docker/ldap-update-univention-object-identifier"
  - IMAGE_NAME: "blocklist-cleanup"
    DOCKERFILE_PATH: "docker/blocklist-cleanup/Dockerfile"

.publish-matrix: &publish-matrix
  - IMAGE_NAME:
      - "udm-rest-api"
      - "udm-rest-api-python-client"
      - "ldap-update-univention-object-identifier"
      - "blocklist-cleanup"

container-build:
  parallel:
    matrix: *build-matrix

container-malware-scan:
  parallel:
    matrix: *publish-matrix

container-sign-external:
  parallel:
    matrix: *build-matrix

test-udm-rest:
  stage: "test"
  extends: .dind
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: "never"
    - when: "on_success"
  image: "${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:27.4.1"
  before_script:
    # Allow that the Docker API version is negotiated between client and server
    - unset DOCKER_API_VERSION
    - export IMAGE_TAG=${RELEASE_VERSION}
    - echo -e "\e[0Ksection_start:`date +%s`:docker_debug[collapsed=true]\r\e[0KDocker version details"
    - echo $IMAGE_TAG
    - docker version
    - echo -e "\e[0Ksection_end:`date +%s`:docker_debug\r\e[0K"
    - cp .env.udm-rest-api.example .env.udm-rest-api
    - mkdir secret
    - echo "univention" > secret/machine.secret
    - echo "univention" > secret/ldap.secret
    - echo -e "\e[0Ksection_start:`date +%s`:docker_compose_config[collapsed=true]\r\e[0KDocker Compose configuration"
    - docker compose config udm-rest-api ldap-server test
    - echo -e "\e[0Ksection_end:`date +%s`:docker_compose_config\r\e[0K"
    - docker compose up --no-build --quiet-pull --wait --wait-timeout 60 udm-rest-api ldap-server
  script:
    - docker compose run --quiet-pull --rm test pytest -lvv tests/integration
  after_script:
    - docker compose down --volumes

test-chart-udm-rest-api:
  stage: test
  needs: []
  image: "gitregistry.knut.univention.de/univention/dev/nubus-for-k8s/common-helm/testrunner:0.24.5@sha256:efa1b3300fca2367e67dec8525c71f5445d75d88ae1da20aa64083a411bc3337"
  script:
    - helm dep build helm/udm-rest-api
    - pytest -W error tests/chart

push-image-external:
  parallel:
    matrix: *publish-matrix

check-debian-updates:
  parallel:
    matrix: *publish-matrix
  variables:
    TARGET_IMAGE: "${CI_REGISTRY_IMAGE}/${IMAGE_NAME}:latest"

sonarqube:
  extends: .sonarqube
  needs: []

...
