---
variables:
  SOUVAP_HELM_PROJECT_ID: 101
  SOUVAP_REGISTRY_PATH: souvap/tooling/images/udm-rest-api

include:
  - project: univention/customers/dataport/upx/common-ci
    file:
      - defaults/souvap-workflow.yaml
      - defaults/stages.yaml
      - templates/kaniko.yaml
      - templates/souvap.yaml
      - jobs/lint-commit-messages.yaml
      - jobs/lint-pre-commit.yaml
      - jobs/package-and-publish-helm-charts.yaml

lint-pre-commit:
  before_script:
    # Compose lint would fail without the referenced env files
    - cp .env.udm-rest-api.example .env.udm-rest-api
    - helm repo add bitnami https://charts.bitnami.com/bitnami

build-udm-rest:
  stage: build
  extends: .kaniko
  needs: []
  variables:
    KANIKO_BUILD_CONTEXT: "docker/udm-rest-api"
    CI_REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE/udm-rest-api"

# TODO: Remove once we drop this job from common-ci
publish-helm-charts:
  rules:
    - when: never

push-image-souvap:
  # TODO, drop once common-ci sets the stage by default
  stage: publish
  needs:
    - job: build-udm-rest
  extends: .push-image-souvap
  variables:
    SOUVAP_IMAGE_NAME: "udm-rest-api"

publish-helm-charts-souvap:
  extends: .publish-helm-charts-souvap

...
