---

name: "dev-local"

services:
  udm-rest-api:
    image: gitregistry.knut.univention.de/univention/customers/dataport/upx/container-udm-rest/udm-rest-api:latest
    build:
      context: ./docker/udm-rest-api
      platforms:
        # FIXME: remove once arm64 packages are available at updates.software-univention.de
        - "linux/amd64"
      target: final
    ports:
      - 9979:9979
    env_file: .env.udm-rest-api
    secrets:
      - machine_secret

  api-client:
    profiles:
      - test
    image: gitregistry.knut.univention.de/univention/customers/dataport/upx/container-udm-rest/udm-rest-api-python-client:${IMAGE_TAG:-latest}
    build:
      context: ./docker/udm-rest-api-python-client
    platform: "linux/amd64"
    working_dir: "/src"
    volumes:
      - "./:/src/"

  pre-commit:
    profiles:
      - "pre-commit"
    image: gitregistry.knut.univention.de/univention/customers/dataport/upx/container-pre-commit/upx-pre-commit:latest
    volumes:
      - type: bind
        source: .
        target: /code
      - type: volume
        # pre-commit installs dependencies, having them cached speeds things up
        # a lot.
        source: pre-commit-cache
        target: /cache

  test:
    profiles:
      - "test"
    platform: "linux/amd64"
    build:
      context: docker/testrunner
    environment:
      PYTEST_ADDOPTS: --udm-rest-url=http://udm-rest-api:9979/udm/
    volumes:
      - type: bind
        source: .
        target: /app/

  ldap-server:
    profiles:
      - "test"
    platform: linux/amd64
    image: gitregistry.knut.univention.de/univention/customers/dataport/upx/container-ldap/ldap-server:latest
    environment:
      DOMAIN_NAME: univention-organization.intranet
      LDAP_BASE_DN: dc=univention-organization,dc=intranet
      LDAP_CN_ADMIN_PW: "univention"
    ports:
      - 389:389
    volumes:
      - ldap-shared-data:/var/lib/univention-ldap/:rw

secrets:
  machine_secret:
    file: secret/machine.secret

volumes:
  pre-commit-cache:
  ldap-shared-data:

...
