---

name: "dev-local"

services:
  udm-rest-api:
    image: gitregistry.knut.univention.de/univention/customers/dataport/upx/container-udm-rest/udm-rest-api:latest
    build:
      context: ./docker/udm-rest-api
      platforms:
        # FIXME: remove once arm64 packages are available at updates.software-univention.de
        - "linux/amd64"
      target: final
    ports:
      - 9979:9979
    env_file: .env.udm-rest-api
    secrets:
      - machine_secret

  udm-rest-cli-client:
    profiles:
      - test
    image: gitregistry.knut.univention.de/univention/customers/dataport/upx/container-udm-rest/udm-rest-cli-client:branch-jbornhold-exp-adjusted-deb-files
    build:
      context: ./docker/udm-rest-cli-client
    platform: "linux/amd64"
    environment:
      # Inject credentials into the wrapper scripts
      UDM_API_URL: "http://udm-rest-api.default/udm/"
      UDM_API_BINDDN: "cn=admin,dc=univention-organization,dc=intranet"
      UDM_API_PASSWORD: "univention"

      # For development
      PYTHONPATH: "/ucs/management/univention-directory-manager-rest/src"
    volumes:
      - "../ucs:/ucs"
      - "../:/root/wu"

  pre-commit:
    profiles:
      - test
    image: gitregistry.knut.univention.de/univention/customers/dataport/upx/container-pre-commit/upx-pre-commit:latest
    volumes:
      - type: bind
        source: .
        target: /code
      - type: volume
        # pre-commit installs dependencies, having them cached speeds things up
        # a lot.
        source: pre-commit-cache
        target: /cache

secrets:
  machine_secret:
    file: secret/machine.secret

volumes:
  pre-commit-cache:

...
