---

name: "dev-local"

services:
  udm-rest-api:
    image: gitregistry.knut.univention.de/univention/customers/dataport/upx/container-udm-rest/udm-rest-api:latest
    build:
      context: ./docker/udm-rest-api
      platforms:
        # FIXME: remove once arm64 packages are available at updates.software-univention.de
        - "linux/amd64"
      target: final
    ports:
      - 9979:9979
    env_file: .env.udm-rest-api
    secrets:
      - ca_cert
      - ldap_secret
      - machine_secret

  pre-commit:
    profiles:
      - test
    image: gitregistry.knut.univention.de/univention/customers/dataport/upx/container-pre-commit/upx-pre-commit:latest
    volumes:
      - type: bind
        source: .
        target: /code
      - type: volume
        # pre-commit installs dependencies, having them cached speeds things up
        # a lot.
        source: pre-commit-cache
        target: /cache

secrets:
  ca_cert:
    file: ssl/certs/CAcert.pem
  ldap_secret:
    file: secret/ldap.secret
  machine_secret:
    file: secret/machine.secret

volumes:
  pre-commit-cache:

...
