# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023-2024 Univention GmbH

---

services:
  udm-rest-api:
    image: gitregistry.knut.univention.de/univention/customers/dataport/upx/container-udm-rest/udm-rest-api:${IMAGE_TAG:-latest}
    # FIXME: remove once arm64 packages are available at updates.software-univention.de
    platform: "linux/amd64"
    build:
      context: ./docker/udm-rest-api
      target: test
    ports:
      - 9979:9979
    env_file: .env.udm-rest-api
    secrets:
      - machine_secret
    volumes:
      - type: bind
        source: ./tests/base.conf
        target: /etc/univention/base.conf
        read_only: true

  api-client:
    profiles:
      - test
    image: gitregistry.knut.univention.de/univention/customers/dataport/upx/container-udm-rest/udm-rest-api-python-client:${IMAGE_TAG:-latest}
    build:
      context: ./docker/udm-rest-api-python-client
    platform: "linux/amd64"
    working_dir: "/src"
    volumes:
      - "./:/src/"

  pre-commit:
    profiles:
      - "pre-commit"
    image: gitregistry.knut.univention.de/univention/customers/dataport/upx/container-pre-commit/upx-pre-commit:${IMAGE_TAG:-latest}
    volumes:
      - type: bind
        source: .
        target: /code
      - type: volume
        # pre-commit installs dependencies, having them cached speeds things up
        # a lot.
        source: pre-commit-cache
        target: /cache

  test:
    profiles:
      - "test"
    platform: "linux/amd64"
    image: gitregistry.knut.univention.de/univention/customers/dataport/upx/container-udm-rest/testrunner:${IMAGE_TAG:-latest}
    build:
      context: docker/testrunner
    environment:
      PYTEST_ADDOPTS: --udm-rest-url=http://udm-rest-api:9979/udm/
    volumes:
      - type: bind
        source: .
        target: /app/

  ldap-server:
    profiles:
      - "test"
    platform: linux/amd64
    image: gitregistry.knut.univention.de/univention/customers/dataport/upx/container-ldap/ldap-server:latest
    build:
      context: ../container-ldap/docker/ldap-server
      target: final
    environment:
      DOMAIN_NAME: univention-organization.intranet
      LDAP_BASE_DN: dc=univention-organization,dc=intranet
      LDAP_CN_ADMIN_PW: "univention"
      TLS_MODE: "off"
    # FIXME: slapd won't work on linux kernel 6.6
    ulimits:
      nofile:
        soft: 1024
        hard: 1024
    ports:
      - 389:389
    volumes:
      - ldap-shared-data:/var/lib/univention-ldap/:rw
      - type: bind
        source: ./tests/base.conf
        target: /etc/univention/base.conf
        read_only: true

  # Environment to build the documentation
  docs:
    image: docker-registry.knut.univention.de/sphinx:latest
    working_dir: /src/docs
    volumes:
      - ".:/src"
    profiles:
      - docs

secrets:
  ldap_secret:
    file: secret/ldap.secret
  machine_secret:
    file: secret/machine.secret

volumes:
  pre-commit-cache:
  ldap-shared-data:

...
