sonar.projectKey=univention_dev_nubus-for-k8s_udm-rest-api_fe3db5cc-43d3-4552-85e3-9b8cf2b9cefd
sonar.qualitygate.wait=true
sonar.python.version=3.11
sonar.links.homepage=https://git.knut.univention.de/univention/dev/nubus-for-k8s/udm-rest-api
sonar.links.issue=https://git.knut.univention.de/univention/dev/internal/team-nubus/-/issues
sonar.links.scm=https://git.knut.univention.de/univention/dev/nubus-for-k8s/udm-rest-api
