---

apiVersion: "v1"
kind: ConfigMap
metadata:
  name: '{{ include "common.names.fullname" . }}'
data:
  CA_CERT_FILE: "{{ .Values.udmRestApi.caCertFile }}"
  # TODO: "ENVIRONMENT" is not yet used
  ENVIRONMENT: "{{ .Values.udmRestApi.environment }}"
  # TODO: "LOG_LEVEL" is not yet used
  LOG_LEVEL: "{{ .Values.udmRestApi.logLevel }}"
  LDAP_ADMIN_PASSWORD: {{ required "The parameter \"udmRestApi.ldap.adminPassword\" is required." .Values.udmRestApi.ldap.adminPassword | quote }}
  LDAP_BASE: {{ required "The parameter \"udmRestApi.ldap.base\" is required." .Values.udmRestApi.ldap.base | quote }}
  LDAP_MACHINE_PASSWORD: {{ required "The parameter \"udmRestApi.ldap.machinePassword\" is required." .Values.udmRestApi.ldap.machinePassword | quote }}
  LDAP_URI: "ldap://{{ required "The parameter \"udmRestApi.ldap.host\" is required." .Values.udmRestApi.ldap.host }}:{{ required "The parameter \"udmRestApi.ldap.port\" is required." .Values.udmRestApi.ldap.port }}"
  TLS_REQCERT: "{{ .Values.udmRestApi.tlsReqcert }}"
  domainname: "{{ .Values.udmRestApi.domainname }}"
  directory__manager__rest__authorized___groups__dc___backup: "{{ .Values.udmRestApi.authGroups.dcBackup }}"
  directory__manager__rest__authorized___groups__dc___slaves: "{{ .Values.udmRestApi.authGroups.dcSlaves }}"
  directory__manager__rest__authorized___groups__domain___admins: "{{ .Values.udmRestApi.authGroups.domainAdmins }}"
  directory__manager__rest__debug__level: "{{ .Values.udmRestApi.apiLogLevel }}"
  directory__manager__templates__alphanum__whitelist:
  directory__reports__templates__csv__computer1: "computers/computer \"CSV Report\" /etc/univention/directory/reports/default computers.csv"
  directory__reports__templates__csv__group1: "groups/group \"CSV Report\" /etc/univention/directory/reports/default groups.csv"
  directory__reports__templates__csv__user1: "users/user \"CSV Report\" /etc/univention/directory/reports/default users.csv"
  directory__reports__templates__pdf__computer1: "computers/computer \"PDF Document\" /etc/univention/directory/reports/default computers.rml"
  directory__reports__templates__pdf__group1: "groups/group \"PDF Document\" /etc/univention/directory/reports/default groups.rml"
  directory__reports__templates__pdf__user1: "users/user \"PDF Document\" /etc/univention/directory/reports/default users.rml"
  directory__manager__user__activate_ldap_attribute_mailForwardCopyToSelf: "yes"
  directory__manager__user_group__uniqueness: "true"
  directory__manager__web__language: "en_US.UTF-8"
  directory__manager__web__modules__autosearch: "1"
  directory__manager__web__modules__computers__computer__add__default: "computers/windows"
  directory__manager__web__modules__groups__group__caching__uniqueMember__timeout: "300"
  directory__manager__web__modules__groups__group__checks__circular_dependency: "yes"
  directory__manager__web__modules__search__advanced_on_open: "false"
  directory__manager__web__modules__users__user__properties__homePostalAddress__syntax: "postalAddress"
  directory__manager__web__modules__wizards__disabled: "no"
  directory__manager__web__sizelimit: "2000"
  directory__reports__cleanup__age: "43200"
  directory__reports__cleanup__cron: "0 0 * * *"
  directory__reports__logo: "/usr/share/univention-directory-reports/univention_logo.png"
  hostname: "{{ .Values.udmRestApi.hostname }}"
  ldap__base: "{{ .Values.udmRestApi.ldap.base }}"
  ldap__master: "{{ .Values.udmRestApi.ldap.host }}"
  ldap__master__port: "{{ .Values.udmRestApi.ldap.port }}"
  ldap__server__name: "{{ .Values.udmRestApi.ldap.host }}"
  ldap__server__port: "{{ .Values.udmRestApi.ldap.port }}"
  ldap__server__ip: "{{ .Values.udmRestApi.ldap.serverIp }}"
  ldap__hostdn: "{{ .Values.udmRestApi.ldap.hostDn }}"

...
