---
{{ include "common.configMap" (dict "top" . "overrides" "udm-rest-api.configMap") }}

{{- define "udm-rest-api.configMap" }}
{{- with .top }}
data:
  LDAP_SECRET_FILE: "{{ .Values.udmRestApi.ldapSecretFile }}"
  MACHINE_SECRET_FILE: "{{ .Values.udmRestApi.machineSecretFile }}"
  CA_CERT_FILE: "{{ .Values.udmRestApi.caCertFile }}"

  # used by the load-join-data job
  UDM_API_URL: 'http://{{ include "common.names.fullname" . }}/udm/'
  UDM_API_USER: "cn=admin"
  UDM_API_PASSWORD_FILE: "{{ .Values.udmRestApi.ldapSecretFile }}"

{{- end }}
{{- end }}
...
