---
{{ include "common.configMap" (dict "top" . "overrides" "udm-rest-api.configMap") }}

{{- define "udm-rest-api.configMap" }}
{{- with .top }}
data:
  DOMAINNAME: "{{ .Values.udmRestApi.domainname }}"
  HOSTNAME: "{{ .Values.udmRestApi.hostname }}"
  LDAP_HOST: {{ required "The parameter \"udmRestApi.ldapHost\" is required." .Values.udmRestApi.ldapHost | quote }}
  LDAP_HOST_IP: "{{ .Values.udmRestApi.ldapHostIp }}"
  LDAP_PORT: {{ required "The parameter \"udmRestApi.ldapPort\" is required." .Values.udmRestApi.ldapPort | quote }}
  LDAP_BASE_DN: {{ required "The parameter \"udmRestApi.ldapBaseDn\" is required." .Values.udmRestApi.ldapBaseDn | quote }}
  LDAP_HOST_DN: {{ required "The parameter \"udmRestApi.ldapHostDn\" is required." .Values.udmRestApi.ldapHostDn | quote }}
  TLS_MODE: {{ required "The parameter \"udmRestApi.tlsMode\" is required." .Values.udmRestApi.tlsMode | quote }}

  DEBUG_LEVEL: "{{ .Values.udmRestApi.debugLevel }}"
  AUTHORIZED_DC_BACKUP: {{ required "The parameter \"udmRestApi.authGroups.dcBackup\" is required." .Values.udmRestApi.authGroups.dcBackup | quote }}
  AUTHORIZED_DC_SLAVES: {{ required "The parameter \"udmRestApi.authGroups.dcSlaves\" is required." .Values.udmRestApi.authGroups.dcSlaves | quote }}
  AUTHORIZED_DOMAIN_ADMINS: {{ required "The parameter \"udmRestApi.authGroups.domainAdmins\" is required." .Values.udmRestApi.authGroups.domainAdmins | quote }}

  LDAP_SECRET_FILE: "{{ .Values.udmRestApi.ldapSecretFile }}"
  MACHINE_SECRET_FILE: "{{ .Values.udmRestApi.machineSecretFile }}"
  CA_CERT_FILE: "{{ .Values.udmRestApi.caCertFile }}"

  # used by the load-join-data job
  UDM_API_URL: 'http://{{ include "common.names.fullname" . }}/udm/'
  UDM_API_USER: "cn=admin"
  UDM_API_PASSWORD_FILE: "{{ .Values.udmRestApi.ldapSecretFile }}"

{{- end }}
{{- end }}
...
