{{/*
# SPDX-FileCopyrightText: 2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only
*/}}

{{- if .Values.blocklistCleanup.enabled }}
---
apiVersion: "batch/v1"
kind: "CronJob"
metadata:
  name: {{ printf "%s-blocklist-cleanup" (include "nubus-common.names.fullnameWithRevision" .) }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .Values.additionalLabels "context" . ) | nindent 4 }}
  {{- include "nubus-common.annotations.render" ( dict
    "values" ( list .Values.additionalAnnotations )
    "context" . )
    | nindent 2 }}
spec:
  schedule: "{{ .Values.blocklistCleanup.schedule }}"
  concurrencyPolicy: "Forbid"
  jobTemplate:
    spec:
      template:
        metadata:
          name: {{ include "common.names.name" . | quote }}
          labels:
            {{- include "common.labels.standard" . | nindent 12 }}
          {{- if .Values.podAnnotations }}
          annotations: {{- include "common.tplvalues.render" (dict "value" .Values.podAnnotations "context" .) | nindent 12 }}
          {{- end }}
        spec:
          restartPolicy: "Never"
          {{- if or .Values.imagePullSecrets .Values.global.imagePullSecrets }}
          imagePullSecrets:
            {{- range .Values.global.imagePullSecrets }}
            - name: {{ . | quote }}
            {{- end }}
            {{- range .Values.imagePullSecrets }}
            - name: {{ . | quote }}
            {{- end }}
          {{- end }}
          {{- if .Values.podSecurityContext.enabled }}
          securityContext: {{- omit .Values.podSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.serviceAccount.create }}
          serviceAccountName: {{ include "common.names.fullname" . | quote }}
          {{- end }}
          containers:
            - name: "blocklist-cleanup"
              {{- if $.Values.containerSecurityContext.enabled }}
              securityContext: {{- omit $.Values.containerSecurityContext "enabled" | toYaml | nindent 16 }}
              {{- end }}
              image: "{{ coalesce .Values.blocklistCleanup.image.registry .Values.global.imageRegistry }}/{{ .Values.blocklistCleanup.image.repository }}:{{ .Values.blocklistCleanup.image.tag }}"
              imagePullPolicy: {{ coalesce .Values.blocklistCleanup.image.imagePullPolicy .Values.global.imagePullPolicy | quote }}

              envFrom:
                - configMapRef:
                    name: {{ include "common.names.fullname" . | quote }}
              volumeMounts:
                - name: credentials-volume
                  mountPath: /etc/ldap.secret
                  subPath: {{ tpl (include "nubus-common.secrets.key" (dict "existingSecret" .Values.ldap.auth.existingSecret "key" "password")) . }}

              resources:
                {{- toYaml .Values.resources | nindent 16 }}
          volumes:
            - name: credentials-volume
              secret:
                defaultMode: 420
                secretName: {{ include "nubus-common.secrets.name" (dict "existingSecret" .Values.ldap.auth.existingSecret "defaultNameSuffix" "ldap" "context" .) }}

...
{{- end }}
