{{/*
SPDX-FileCopyrightText: 2024-2025 Univention GmbH
SPDX-License-Identifier: AGPL-3.0-only
*/}}
{{- range .Values.extraSecrets }}
---
kind: "Secret"
apiVersion: "v1"
metadata:
  name: {{ .name | quote }}
  namespace: {{ include "common.names.namespace" $ | quote }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" $.Values.additionalLabels "context" $ ) | nindent 4 }}
  {{- include "nubus-common.annotations.render" ( dict
    "values" ( list $.Values.additionalAnnotations )
    "context" $ )
    | nindent 2 }}
{{- if .data }}
data:
{{- range $k, $v := .data }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
{{- end }}
{{- if .stringData }}
stringData:
{{- range $k, $v := .stringData }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
{{- end }}
...
{{- end }}
