# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024-2025 Univention GmbH

{{- if .Values.ingress.enabled }}
---
apiVersion: {{ include "common.capabilities.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.additionalLabels "context" . ) | nindent 4 }}
  annotations:
    {{- if or .Values.ingress.annotations .Values.additionalAnnotations }}
    {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.ingress.annotations .Values.additionalAnnotations ) "context" . ) }}
    {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 4 }}
    {{- end }}
    {{- if .Values.ingress.certManager.enabled }}
    cert-manager.io/{{ .Values.ingress.certManager.issuerRef.kind | kebabcase }}: "{{ coalesce .Values.global.certManagerIssuer .Values.ingress.certManager.issuerRef.name }}"
    {{- end }}
spec:
  {{- if or .Values.ingress.ingressClassName .Values.global.ingressClass }}
  ingressClassName: {{ coalesce .Values.ingress.ingressClassName .Values.global.ingressClass | quote }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ tpl .Values.ingress.host . | quote }}
      secretName: {{ include "udm-rest-api.ingress.tls.secretName" . | quote }}
  {{- end }}
  rules:
    - host: {{ required "The hostname has to be set in \"ingress.host\"." (tpl .Values.ingress.host .) | quote }}
      http:
        paths:
          {{- range .Values.ingress.paths }}
          - pathType: {{ .pathType }}
            path: {{ tpl .path $ }}
            backend: {{- include "common.ingress.backend" (dict "serviceName" (include "common.names.fullname" $) "servicePort" "http" "context" $) | nindent 14 }}
          {{- end }}

...
{{- end }}
