{{- if .Values.udmRestApi.loadJoinData.enabled }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      name: {{ include "common.names.name" . }}
      labels:
        {{- include "common.labels.standard" . | nindent 8 }}
    spec:
      restartPolicy: OnFailure
      {{- with (coalesce .Values.image.pullSecrets .Values.imagePullSecrets) }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: load-join-data
        {{- with .Values.image.loadJoinData }}
        image: "{{ .registry }}/{{ .repository }}{{ if .sha256 }}@sha256:{{ .sha256 }}{{ else }}:{{ .tag }}{{ end }}"
        imagePullPolicy: "{{ .pullPolicy }}"
        {{- end }}
        envFrom:
          - configMapRef:
              name: {{ include "common.names.fullname" . }}
        volumeMounts:
          - name: secrets
            # TODO: conflict with /run/secrets, should use a namespace
            mountPath: /var/secrets
      volumes:
      - name: secrets
        secret:
          secretName: {{ include "common.names.fullname" . | quote }}
{{- end }}
