apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: '{{ include "common.names.fullname" . }}'
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data:
  ldap_secret: {{ .Values.udmRestApi.ldapSecret | quote }}
  machine_secret: {{ .Values.udmRestApi.machineSecret | quote }}
  ca_cert: {{ .Values.udmRestApi.caCert | quote }}
