# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023 Univention GmbH

---
{{ include "common.secret" (dict "top" . "overrides" "udm-rest-api.secret") }}

{{- define "udm-rest-api.secret" }}
{{- with .top }}
data:
  ldap_secret: {{ .Values.udmRestApi.ldapSecret | quote }}
  machine_secret: {{ .Values.udmRestApi.machineSecret | quote }}
  ca_cert: {{ .Values.udmRestApi.caCert | quote }}
{{- end }}
{{- end }}
