# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023-2024 Univention GmbH

---
# Dummy values for running the Helm linter on the udm-rest-api.
# Run it like this: helm lint -f values.yaml -f linter_values.yaml .
global:
  nubusDeployment: false
  ldap:
    uri: "ldap://example-ldap-server:389"
    baseDn: ""
  configMapUcr: "stack-data-ums-ucr"
  systemExtensions:
    - name: "portal"
      image:
        repository: "nubus/images/portal-extension"
        tag: "0.44.3@sha256:734efc0adda680526dde09387db964612f9e0ab020382580984488cc993c68f0"

# -- Kubernetes ingress
ingress:
  # -- Set this to `true` in order to enable the installation on Ingress related objects.
  enabled: false
  host: "nubus.example.com"

extraSecrets:
  - name: nubus-rest-api-credentials
    stringData:
      ldap.secret: "univention"
      machine.secret: "univention"

udmRestApi:
  ldap:
    baseDn: "dc=example,dc=com"
    auth:
      existingSecret:
        name: "udm-rest-api-ldap-credentials"
  image:
    repository: "univention/customers/dataport/upx/container-udm-rest/udm-rest-api"
    imagePullPolicy: "IfNotPresent"
    tag: "0.9.0@sha256:f5589a1a885e9f96d98304148bac5a40dfd4350ee40205a29b8798b29ae0a7db"
...
