# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023-2025 Univention GmbH

---
global:
  nubusDeployment: false
  ldap:
    uri: "ldap://example-ldap-server:389"
    baseDn: ""
  configMapUcr: "stack-data-ums-ucr"
  systemExtensions:
    - name: "portal"
      image:
        repository: "nubus/images/portal-extension"
        tag: "0.44.3@sha256:734efc0adda680526dde09387db964612f9e0ab020382580984488cc993c68f0"

additionalAnnotations:
  "stub-annotation": "stub-value"

podAnnotations:
  "pod-annotation": "pod-stub-value"

ingress:
  enabled: false
  host: "nubus.example.com"

extraSecrets:
  - name: "nubus-rest-api-credentials"
    stringData:
      ldap.secret: "univention"
      machine.secret: "univention"

udmRestApi:
  ldap:
    baseDn: "dc=example,dc=com"
    auth:
      existingSecret:
        name: "udm-rest-api-ldap-credentials"
        keyMapping:
          password: null
  image:
    repository: "univention/dev/nubus-for-k8s/udm-rest-api/udm-rest-api"
    tag: "0.9.0@sha256:f5589a1a885e9f96d98304148bac5a40dfd4350ee40205a29b8798b29ae0a7db"
...
