---
# Dummy values for running the Helm linter on the udm-rest-api.
# Run it like this: helm lint -f values.yaml -f linter_values.yaml .

## Global values
affinity: {}
environment: {}
fullnameOverride: ""
nameOverride: ""
nodeSelector: {}
podAnnotations: {}
podSecurityContext: {}
replicaCount: 1
securityContext: {}
tolerations: []


# -- Application configuration of the UDM REST API
udmRestApi:


# -- Kubernetes ingress
ingress:
  # -- Set this to `true` in order to enable the installation on Ingress related objects.
  enabled: false
  host: "udm.example.develop.souvap-univention.de"


## Istio support
istio:
  # -- Set this to `true` in order to enable the installation on Istio related objects.
  enabled: true
  host: "udm.example.develop.souvap-univention.de"


## Docker image
image:
  tag: "branch-feature-example"


## Container deployment probes
probes:
  liveness:
    enabled: false

  readiness:
    enabled: false

...
