# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023-2025 Univention GmbH

---
global:
  configMapUcr: "stack-data-ums-ucr"
  systemExtensions:
    - name: "portal"
      image:
        repository: "nubus/images/portal-extension"
        tag: "0.44.3@sha256:734efc0adda680526dde09387db964612f9e0ab020382580984488cc993c68f0"

additionalAnnotations:
  "stub-annotation": "stub-value"

podAnnotations:
  "pod-annotation": "pod-stub-value"

ingress:
  enabled: false
  host: "nubus.example.com"

ldap:
  baseDn: "dc=example,dc=com"
  connection:
    uri: "ldap://example-ldap-server:389"
  auth:
    password: "stub-password-linter-values"
