ARG UCS_BASE_IMAGE=gitregistry.knut.univention.de/univention/components/ucs-base-image/ucs-base-506
ARG UCS_BASE_IMAGE_TAG=0.10.0

FROM ${UCS_BASE_IMAGE}:${UCS_BASE_IMAGE_TAG} as final

RUN apt-get update
