# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023-2025 Univention GmbH

---
- name: Fetch secrets from UCS machine
  hosts: ucs_primary

  tasks:
    - name: Fetch LDAP password
      ansible.builtin.fetch:
        src: /etc/ldap.secret
        dest: ../secret/ldap.secret
        flat: true

    - name: Fetch machine.secret
      ansible.builtin.fetch:
        src: /etc/machine.secret
        dest: ../secret/machine.secret
        flat: true

    - name: Fetch CAcert.pem
      ansible.builtin.fetch:
        src: /etc/univention/ssl/ucsCA/CAcert.pem
        dest: ../ssl/certs/CAcert.pem
        flat: true

    - name: Register LDAP base dn from UCR
      ansible.builtin.command: ucr get ldap/base
      register: ldap_base_dn

    - name: Register LDAP host dn from UCR
      ansible.builtin.command: ucr get ldap/hostdn
      register: ldap_host_dn

    - name: Register local hostname
      ansible.builtin.command: hostname -s
      register: local_hostname
      delegate_to: localhost

    - name: Register local domainname
      ansible.builtin.command: hostname -d
      register: local_domainname
      delegate_to: localhost

    - name: Register local operating system
      ansible.builtin.command: uname -s
      register: local_os
      delegate_to: localhost

    - name: Configure .env.udm-rest
      ansible.builtin.template:
        src: ./templates/dotenv.udm-rest-api.j2
        dest: ../.env.udm-rest-api
      delegate_to: localhost

    - name: Configure docker-compose.override.yaml
      ansible.builtin.template:
        src: ./templates/docker-compose.override.yaml.j2
        dest: ../docker-compose.override.yaml
      delegate_to: localhost
